spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jackieathome?useSSL=false
    username: root
    password: mypassword
    # 6.x版本的MySQL JDBC驱动类为com.mysql.cj.jdbc.Driver
    # 5.X版本的MySQL JDBC驱动类为com.mysql.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver