spring:
  datasource:
    url: jdbc:mysql://rm-m5etk9y1cw8uh08c9ro.mysql.rds.aliyuncs.com:3306/qdu?useSSL=false&useUnicode=true&characterEncodeing=UTF-8
    username: wangxi
    password: Wangxi1023%123
    # 6.x版本的MySQL JDBC驱动类为com.mysql.cj.jdbc.Driver
    # 5.X版本的MySQL JDBC驱动类为com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
redis:
  database: 1
  host: 127.0.0.1
  password: 12345
  port: 6379
  timeout: 3000
  jedis:
    pool:
      max-idle: 500
      min-idle: 50
      max-active: 2000
      max-wait: 1000
  testOnBorrow: true